### ISSUE TITLE
Exception: "Something bad happened"

### ISSUE THREAD

**Issue by milesizzo** [maxmind/MaxMind-DB-Reader-php#111]
Hi all,

I'm trying to track down this error, which occurs in the `findAddressInTree` method in `Reader`. The error occurs in my Slim 4 application, which accesses the reader via middleware (in the `process` method):
```
...
$reader = new Reader($this->dbFilename);
$record = $reader->get($ip);
$request = $request->withAttribute('country_code', $record['country']['iso_code']);
...
```

I don't get the error when I manually access the database from a simple command line script:
```
<?php

require '/path/to/vendor/autoload.php';

$reader = new \MaxMind\Db\Reader('/path/to/GeoIP2-Country.mmdb');
var_dump($reader->get("IP_GOES_HERE")['country']['iso_code']);
```

This is in PHP 7.4 (using PHP-FPM and Apache 2.4.29), and I'm using version 1.8.0 of the MaxMind DB reader, with the extension compiled and enabled. Note that I had this same error prior to using the extension, and also with the `geoip2` package.

What does this error mean, and do you have any suggestions on how I can proceed with debugging it?

**Comment by oschwald** [comment]
That sounds like an error displayed to the end user by your web server. Do you have the error as recorded in the log file?

**Comment by oschwald** [comment]
I apologize. A colleague pointed out that we do have an exception with that error text. It would only happen if the database was corrupt or invalid.

**Comment by milesizzo** [comment]
Excellent, thank you for the additional info!

Offhand you couldn't think of something that might cause this as a side-effect (say, caching a `Reader` object in APCu or using opcache)? I'm confused why it works via command line and not in PHP-FPM (fully suspecting that it's my code causing the issue).

**Comment by milesizzo** [comment]
And as a follow-up question: should this code path ever even be called if I'm using the extension correctly?

**Comment by oschwald** [comment]
If the C extension is loaded, this code should not be called at all.

This could potentially happen if you update the database file in a non-atomic way (e.g., just copying the new file over the old file). The pure PHP reader also has an open file handle so anything that could mess up the state of the file handle could potentially cause issues, although I would generally expect the exception message to be different.

**Comment by milesizzo** [comment]
Thanks. I'll continue my search. First port of call is to figure out why the extension isn't being loaded. Thanks, I'll post my findings if it may help others.

**Comment by milesizzo** [comment]
Well I'm still not sure why the pure PHP library encountered that exception, but I've managed to get the extension working and all is well. The problem there was purely my own fault: I was using `php-config --extension-dir` to find where to deploy `maxminddb.so`, but hadn't installed the `php-dev` package (`php7.4-dev`) in my deploy scripts. So it worked in my test environment, but not in production.

For anyone who comes across this and is unsure how to do this in Ubuntu (or even a Github action):
```
# add-apt-repository -y ppa:maxmind/ppa
# apt-get -qq -y install libmaxminddb0 libmaxminddb-dev mmdb-bin
# cp path/to/your/maxminddb.ini /etc/php/7.4/mods-available
# cp path/to/your/maxminddb.so $(php-config --extension-dir)
# phpenmod maxminddb
```

The contents of my `maxminddb.ini` is simply:
```
extension=maxminddb.so
```

Note that I also removed `maxmind-db/reader` from my `composer.json` and added `"ext-maxminddb": "*"`.

**Comment by oschwald** [comment]
I am glad you got the extension working! I'll go ahead and close this, but please do feel free to reopen it if you ever narrow down the issue you were experiencing with the pure PHP reader.
