### ISSUE TITLE
TypeError in Db\Reader\Decoder with bcmath extension

### ISSUE THREAD

**Issue by dodo1708** [maxmind/MaxMind-DB-Reader-php#124]
# Desription

When reading from the database, I get the following error message:
`bcadd() expects parameter 1 to be string, int given`

Error location: `src/MaxMind/Db/Reader/Decoder.php:296`

# Reproduce

- used database type: ISP
- looked up IP-Address: `195.66.12.14`
- GeoIP2 version: v2.11.0

# Proposed fix

Instead of 
```
$pointer = bcadd($pointerOffset, (string) $this->pointerBase);
```
use
```
$pointer = (int) bcadd((string) $pointerOffset, (string) $this->pointerBase);
```
First Argument has to be `string` (but is `int`) and return value needs to be `int` (required in `decode` line 76)

**Comment by dodo1708** [comment]
I'm using a docker environment with the following system attributes (php -i):
Linux 532f790ad4b5 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64

**Comment by oschwald** [comment]
If this is happening on a 64-bit PHP build, then your database is likely
corrupt. A pointer should never be large enough to hit this code with
64-bit integers.
