### ISSUE TITLE
[feature request] MMDB writer

### ISSUE THREAD

**Issue by Niek** [maxmind/MaxMind-DB-Reader-php#127]
Are there any plans to add writer functionality, similar to the perl library?

References:
https://blog.maxmind.com/2015/09/29/building-your-own-mmdb-database-for-fun-and-profit/
https://github.com/maxmind/MaxMind-DB-Writer-perl

**Comment by oschwald** [comment]
No, we don't plan on adding a PHP MMDB writer. In addition to the Perl one, we have a [Go version](https://github.com/maxmind/mmdbwriter).

**Comment by Niek** [comment]
Thanks - I was not aware of the Go version, but that is a good alternative. I've used the Perl one as well but the CPAN dependencies are a mess.
