### ISSUE TITLE
Performance issue, There are any other option for performance?

### ISSUE THREAD

**Issue by dbwodlf3** [maxmind/MaxMind-DB-Reader-php#154]
I am using MaxMind\Db\Reader. but this is so slow.
```php
$reader = new MaxMind\Db\Reader("GeoIP.mmdb");
$reader->get($ip)
```
I don't know why this is so slow. (There are any other overhead? my code doesn't create new connector, just reuse it.)

I can imagin just upload ip->name mapped associated array to memory and just read ip!

There are any option?

thanks.

**Comment by oschwald** [comment]
There is a [C extension](https://github.com/maxmind/MaxMind-DB-Reader-php#optional-php-c-extension) that will greatly improve the performance of reading MMDB files.

If a CSV is a better fit for your use case, MaxMind also provides CSV files.
