### ISSUE TITLE
Error "The MaxMind DB file's search tree is corrupt" for GeoLite2

### ISSUE THREAD

**Issue by asistent0** [maxmind/MaxMind-DB-Reader-php#156]
Hi.

I use the gpslab/geoip2 library. And use it to load the GeoLite2-City database. But when using, when trying to determine the ip, the error "MaxMind DB file search tree is corrupted" is displayed.

    #file: "vendor\maxmind-db\reader\src\MaxMind\Db\Reader.php"
    #line: 285

After reading a little code, I realized that there is a file check for the required size, which should be 102 MB, and my file weighs only 70 MB. I even tried downloading the database separately from the site https://www.maxmind.com/en/accounts/current/geoip/downloads, but I use the most recent file as on the site.

Tell me what can be done, how to get around this error so that the library accepts the correct file of a smaller size.

**Comment by oschwald** [comment]
The only file size limit in this library is the maximum size supported by the database format. There is no minimum size specified. Are you sure you decompressed the file before passing it to this library? I would also double check that the sha256 of the file matches the one on the download site.

If you have further questions, I suggest contacting [support@maxmind.com](mailto:support@maxmind.com) or using the chat pop-up on www.maxmind.com.
