### ISSUE TITLE
Potential issue with 128-bit integers?

### ISSUE THREAD

**Issue by LauraTaylorUK** [maxmind/MaxMind-DB-Reader-php#162]
I am not sure if this is an issue or not, I could not test because the current database does not use this integer type.

The function `decodeUint()` returns `int|string`. When using real ints, it returns `int` and when using 128-bit integers with the gmp or bcmath exntensions then it returns `string`.

This means that the function `decodePointer()` with `$pointerSize` case equal to `4` will use the result in a math operation:
`$pointer = $pointerOffset + $pointerBase;` (file Decoder.php, line 321).

Thus, PHP will try to add the integer `$pointerBase` with the string representation of the 128-bit integer. Potentially adding a string will fail, but I could not verify this.

**Comment by oschwald** [comment]
A pointer of size 4 would be a 32 bit unsigned integer so this won't be a problem. Also, PHP will happily add a string and an integer, but if the result is larger than `PHP_INT_MAX`, it will be converted to a floating point type.
