### ISSUE TITLE
Fedora RPM package php-maxmind-db-reader-1.11.0-7.fc38.noarch

### ISSUE THREAD

**Issue by LauraTaylorUK** [maxmind/MaxMind-DB-Reader-php#164]
Hello,

I am not sure if this is the correct place to mention this, but the Fedora packages are missing a dependency for: `php-fedora-autoloader`

Without the `php-fedora-autoloader` package, the library fails to load. It should be included in the SPEC file as a requirement.

Thank you.

**Comment by remicollet** [comment]
@LauraTaylorUK please use https://bugzilla.redhat.com/
