### ISSUE TITLE
Db/Reader.php / Util.php : Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by bplace** [maxmind/MaxMind-DB-Reader-php#165]
Hello,

I get a little bunch of fatal errors sometimes on Db/Reader.php or Db/Reader/Util.php (Maximum execution time of 30 seconds exceeded).

The env is Debian 11 + Nginx, I'm using GeoLite2-Country.mmdb as follows (inside try / catch, result is cached):

```
$reader  = new Reader(APPLICATION_PATH . '/models/GeoLite2-Country.mmdb'); // Exception si DB down
$record  = $reader->country($_SERVER['REMOTE_ADDR']);
$isocode = $record->country->isoCode;
```

Util.php just read / seek / tell on the file, so I'm a bit clueless. I didn't find any hint in the syslog of the server. Looks like a file lock...

Any way to handle this properly?

**Comment by oschwald** [comment]
I haven't heard reports of this previously. As you saw, it is just seeking and reading from the file. There isn't any special file locking happening within the library. Is the file on a local drive or is it a network drive?

**Comment by bplace** [comment]
It's on a local file, this doesn't happen during the DB update neither. This issue has been poping for years, usually a quick 2-3 seconds of fatal errors. 

The GeoIP part of the app is not very important, I could perfectly default to US if the GeoIP record can't be read in less than 500ms.

**Comment by oschwald** [comment]
I am going to close this issue as it doesn't seem actionable. As mentioned above, we are just using normal file operations  in this code and there is no locking or anything that we are doing.

It is possible that switching [the C extension](https://github.com/maxmind/MaxMind-DB-Reader-php#optional-php-c-extension) would fix the issue for you, as it doesn't access the file through PHP file operations and uses mmap. It would also improve the performance generally.
