### ISSUE TITLE
Where does the documentation for this extension reside?

### ISSUE THREAD

**Issue by Girgias** [maxmind/MaxMind-DB-Reader-php#167]
I've been looking at doing some clean-up of the php.net documentation, and one candidate for removal is the GeoIP docs which as far as I understand refer to the now deprecated and EOL legacy extension, however the PECL page for this extension also links to those legacy docs.

My question is, where does the documentation actually live and if it is possible to update the PECL page/package.xml to point to the correct place. Also, to remove the legacy docs from the php.net website as they are not in great shape.

**Comment by BelleNottelling** [comment]
It doesn't look like there's anything for them to document outside what's already in the readme (maybe some info on error handling, if any?).
The `get` and `getWithPrefixLen` functions simply return an array.

## `get`
```PHP
Array
(
    [autonomous_system_number] => 12874
    [autonomous_system_organization] => FASTWEB
    [country] => Array
        (
            [iso_code] => IT
        )

)
```

## `getWithPrefixLen`
```PHP
Array
(
    [0] => Array
        (
            [autonomous_system_number] => 12874
            [autonomous_system_organization] => FASTWEB
            [country] => Array
                (
                    [iso_code] => IT
                )

        )

    [1] => 17
)
```

I suspect most will want to use the [GeoIP2-php](https://github.com/maxmind/GeoIP2-php) package which builds on top of this one and that has what appears to be pretty full documentation in it's readme with anything missing coming from PHPDocs.

**Comment by oschwald** [comment]
That is correct. We don't currently have separate documentation for the extension. The README provides some usage information and there are PHPDocs for the pure PHP implementation, which has the same API. As mentioned above, we expect most people to be using it through the higher-level GeoIP2 API rather than directly. That said, I think we'd be open to maintaining documentation similar to the `geoip` extension documentation on php.net. The API of the extension is quite simple. It would be nice if that could be exported from the PHPDocs in the PHP code, but it isn't essential.

**Comment by Girgias** [comment]
> That is correct. We don't currently have separate documentation for the extension. The README provides some usage information and there are PHPDocs for the pure PHP implementation, which has the same API. As mentioned above, we expect most people to be using it through the higher-level GeoIP2 API rather than directly. That said, I think we'd be open to maintaining documentation similar to the `geoip` extension documentation on php.net. The API of the extension is quite simple. It would be nice if that could be exported from the PHPDocs in the PHP code, but it isn't essential.

This is just what I wanted to confirm.

Personally, I prefer to _not_ have the extension documentation on php.net as a lot of extension maintainers forget about it and might write documentation in a style that is inconsistent with the "core" manual which php-src has control over.

But I have got the info I wanted, which is that the ``geoip`` documentation on php.net can be removed after we do an archive again for it.

**Comment by stevebauman** [comment]
Sorry to revive an old thread, but I'm having a hard time figuring out how to use the extension at all outside of installing it. Did they get moved somewhere? Could someone point me to the docs? 🙏

**Comment by stevebauman** [comment]
Thanks for the quick reply @oschwald! 🙏 

Sorry, just to clarify: that means if I'm using [GeoIP2-php](https://github.com/maxmind/GeoIP2-php) and I install the extension -- GeoIP2-php will use the extension instead of its PHP-based DB reader automatically?

**Comment by oschwald** [comment]
Yes, the GeoIP2 reader will automatically use this extension if it is loaded. There is no need for code change on your end.

**Comment by stevebauman** [comment]
Ok awesome thanks guys! Really appreciate your help 🙏
