### ISSUE TITLE
PHP_MAXMINDDB_VERSION has not been updated

### ISSUE THREAD

**Issue by thias** [maxmind/MaxMind-DB-Reader-php#19]
I have built the extension at tag version 1.0.0 and phpinfo() shows that it's loaded, but says it's version 0.2.0. In `ext/php_maxminddb.h` I can see `#define PHP_MAXMINDDB_VERSION` setting this. Shouldn't this have been updated, and keep being updated with future releases?

**Comment by oschwald** [comment]
Yes, thanks for bringing this to our attention.

**Comment by oschwald** [comment]
This was fixed in 1.0.1. I added a release script to automatically update the version going forward.
