### ISSUE TITLE
get model by other properties than IP

### ISSUE THREAD

**Issue by timersys** [maxmind/MaxMind-DB-Reader-php#22]
Hi It would be great if we can get the country or city model for example by Iso code, country name, etc
It's possible? I tried to look the code by I get lost in findAddressInTree :(

**Comment by oschwald** [comment]
The database is optimized for looking up records by IP address. The first half of it is essentially a binary tree for subnets. It would be extremely resource intensive to look up by other properties. I would suggest looking at using the data from [GeoNames](http://www.geonames.org/) for this purpose.
