### ISSUE TITLE
I got this exception after integrated into my project.

### ISSUE THREAD

**Issue by thirumala548** [maxmind/MaxMind-DB-Reader-php#23]
My project is in ZEND framework.
My project having many soap calls.
I got an error regarding to maxmind DB.
I integrate the maxmind DB by using the "https://github.com/maxmind/MaxMind-DB-Reader-php"

 Fatal error: Maximum execution time of 30 seconds exceeded in C:\wamp\www\library\Zend\Loader\Autoloader.php on line 114

**Comment by oschwald** [comment]
This sounds like an issue with the Zend autoloader. I am not sure if there is anything we can fix, at least without more information on if and how our package is causing the issue. I'd suggest asking for help from Zend's support or community.
