### ISSUE TITLE
Get ISP by it's AS number

### ISSUE THREAD

**Issue by jappievw** [maxmind/MaxMind-DB-Reader-php#26]
For an administrative system we want to do a database lookup based on the as number in the ISP database. Currently, lookups can only be based on IP address. Is there any way in which this can be supported?

**Comment by oalders** [comment]
@jappievw at this moment, no.  The mmdb format is set up to key everything based on IP addresses, so I don't think there's an efficient way to do what you want in this case.  For more info, you can have a look at the mmdb spec https://github.com/maxmind/MaxMind-DB/blob/master/MaxMind-DB-spec.md

**Comment by jappievw** [comment]
Thanks for the clarification @oalders!
