### ISSUE TITLE
C extension for HHVM

### ISSUE THREAD

**Issue by dcro** [maxmind/MaxMind-DB-Reader-php#28]
Any chance to get a HHVM version of the MaxMind DB Reader extension?

**Comment by oschwald** [comment]
This isn't currently on our roadmap but a PR would be welcomed. The pure PHP implementation has reasonably decent performance on HHVM.

**Comment by madsem** [comment]
@oschwald why not on roadmap if I may ask? Geoip2 library says:

> This library works and is tested with HHVM.


Depends on DB reader, but HHVM users can't use the C extension? Would be great if this would be on the roadmap... Makes sense or not? :+1:

**Comment by oschwald** [comment]
We haven't seen that much demand for an HHVM extension, especially now that PHP 7 is out. To provide direct support for HHVM, we would likely have to create and maintain a completely separate extension. You could, however, try the [HHVM Zend compatibility layer](https://github.com/facebook/hhvm/tree/master/hphp/runtime/ext_zend_compat). It may work with minimal changes.

**Comment by madsem** [comment]
Thanks for this tip, will check it out

**Comment by dcro** [comment]
I should note that I've indeed migrated all the high-traffic servers where I needed this from HHVM to PHP7 and the PHP7 extension with good results. I would rather see the development effort be put into improving that PHP7 extension instead as HHVM usage will most likely drop in the future.

**Comment by oschwald** [comment]
I am going to close this given the divergent paths of PHP and HHVM.
