### ISSUE TITLE
Provide package in PPA

### ISSUE THREAD

**Issue by joshuaspence** [maxmind/MaxMind-DB-Reader-php#29]
https://github.com/maxmind/libmaxminddb is avialable from `ppa:maxmind/ppa` but this package is not. Is it possible to add this package to the PPA so that we don't need to manually compile it?

**Comment by oschwald** [comment]
Thanks for the idea. We may consider this in the future.

**Comment by DocumentRoot** [comment]
Is there any news on this?

I'm sure most of people still using legacy db just because they have 'apt-get install php*-geoip'

Will be awesome to get this extension without compiling, at least from your repository.

**Comment by wens** [comment]
FWIW I've done a debian package branch:

https://github.com/wens/MaxMind-DB-Reader-php/tree/debian

I might setup a personal PPA to host it.

**Comment by alexef** [comment]
Any update on it?

**Comment by sgreiner** [comment]
https://launchpad.net/~sgreiner/+archive/ubuntu/maxminddb
Here you find my unofficial ubuntu packages, I try to update them from time to time on supported distros.

**Comment by oschwald** [comment]
I am going to go ahead and close this. Debian has the current version of this library, and I don't think we are in the best position to maintain high quality PHP deb packages. In most cases, you will be better of with what comes with the distribution.
