### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by JoyceBabu** [maxmind/MaxMind-DB-Reader-php#33]
Is the extension compatible with PHP7? If not, is there any immediate plans to update it to support the new version?

**Comment by davidsarkany** [comment]
Compatible

**Comment by JoyceBabu** [comment]
Thank you for the quick response.

**Comment by lilongyue** [comment]
hi , i meet this :Unable to load dynamic library '/opt/remi/php70/root/usr/lib64/php/modules/maxminddb.so' - /opt/remi/php70/root/usr/lib64/php/modules/maxminddb.so: undefined symbol: zval_used_for_init in Unknown on line 0  ,do you know how to solve this? thank you.
