### ISSUE TITLE
PECL package

### ISSUE THREAD

**Issue by slashterix** [maxmind/MaxMind-DB-Reader-php#34]
Should this be added to the PECL repository for easy download and access?

**Comment by oschwald** [comment]
We [started the process](http://comments.gmane.org/gmane.comp.php.pecl.devel/10425) to make this into a PECL a while back, but no one offered to sponsor us. Also, this extension isn't the greatest fit for PECL due to its dependency on pure PHP code. We have been hoping that [Composer would get extension support](https://github.com/composer/composer/pull/2898) as this would be much preferable.

**Comment by chasebolt** [comment]
I too would like to see this in PECL :+1:

**Comment by demofly** [comment]
Hi there! When it will be in PECL?

**Comment by jbboehr** [comment]
@oschwald I've recently obtained a PECL account. I think I'm able to sponsor you even though I'm a new user, although I don't think I'm able to approve the account request, if you're still interested.

**Comment by oschwald** [comment]
@jbboehr, thanks! That might be helpful. I'll look into it again after the Black Friday / Cyber Monday rush.

**Comment by mmoll** [comment]
any updates here? :)

**Comment by kabudu** [comment]
any update on getting this into PECL?

**Comment by Gemorroj** [comment]
@oschwald Is PECL still supported?

**Comment by oschwald** [comment]
PECL has never been supported for this library. Ideally, Composer would get some sort of meaningful support for extensions, e.g., using Pickle. Having the current extension in PECL isn't ideal unless we make it completely independent of the PHP code in this repo.

**Comment by remicollet** [comment]
I really think having such extension on PECL is useful, at least it will give it much more visibility.
And probably, I can also be a sponsor if needed

> its dependency on pure PHP code. 

Indeed, the metadata method is really strange, having to call pure PHP code.
Shouldn't this method return raw data, and then the pure PHP library can use it ?

**Comment by szepeviktor** [comment]
Having a composer package and a PECL extension in one repo may hold back both software.

**Comment by TBK** [comment]
Any update on this issue?

**Comment by oschwald** [comment]
There are no immediate plans. I think to make this really work as a PECL package, we would want the extension to not depend on any of the pure PHP code (e.g., for exceptions). Once that is done, we could look into getting this on PECL.

**Comment by mkormendy** [comment]
@remicollet is correct, adding this to PECL doesn't require pure PHP code specifically, it would just return the raw data, and then the pure PHP library can use it.

**Comment by oschwald** [comment]
As mentioned above, we would need to remove the use of the pure PHP classes from this extension. Ideally, we would just port them to the extension so that there are no API changes.

**Comment by oschwald** [comment]
I think we are ready to pursue this again. Last time we tried, we didn't get any offers for sponsorship. @jbboehr or @remicollet, are either of you still willing to serve as a sponsor? Thanks!

**Comment by remicollet** [comment]
Yes I can help with publishing this extension on pecl.

**Comment by oschwald** [comment]
@remicollet, thanks! I'll go ahead and apply for an account with you as a sponsor. Once I have that, I am sure there will be follow-up questions and advice that I will need, but that can wait until after your holidays.

**Comment by remicollet** [comment]
Per new extension process, please send a email to pecl dev ML, introducing yourself and the extension.

**Comment by oschwald** [comment]
Thanks! I did when we first pursued getting an account, but it looks like that was way back in 2013. :slightly_smiling_face:

**Comment by oschwald** [comment]
An update:

The intent was to release 1.7.0 as a PECL package, as the release notes suggest. However, we have run into some issues with the PECL servers rejecting the package for reason that are not clear to anyone. There is unfortunately no ETA on when this will be resolved.

**Comment by oschwald** [comment]
The upload issue has been resolved and the package has been successfully uploaded. :fireworks:

**Comment by szepeviktor** [comment]
Thank you @oschwald 

This is very normal :) https://pecl.php.net/package/maxminddb

**Comment by mlocati** [comment]
Thank you very much for this! Adding support for the `maxminddb` PECL package to my [docker PHP extension installer script](https://github.com/mlocati/docker-php-extension-installer) has been a piece of cake.

**Comment by kocoten1992** [comment]
it doesnt work for me:

```
pecl install maxminddb
```

```
...
running: make
/bin/bash /tmp/pear/temp/pear-build-rootA7YtBy/maxminddb-1.8.0/libtool --mode=compile cc  -I. -I/tmp/pear/temp/maxminddb/ext -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootA7YtBy/maxminddb-1.8.0/include -I/tmp/pear/temp/pear-build-rootA7YtBy/maxminddb-1.8.0/main -I/tmp/pear/temp/maxminddb/ext -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/maxminddb/ext/maxminddb.c -o maxminddb.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/maxminddb/ext -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rootA7YtBy/maxminddb-1.8.0/include -I/tmp/pear/temp/pear-build-rootA7YtBy/maxminddb-1.8.0/main -I/tmp/pear/temp/maxminddb/ext -I/usr/include/php/20190902 -I/usr/include/php/20190902/main -I/usr/include/php/20190902/TSRM -I/usr/include/php/20190902/Zend -I/usr/include/php/20190902/ext -I/usr/include/php/20190902/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/maxminddb/ext/maxminddb.c  -fPIC -DPIC -o .libs/maxminddb.o
/tmp/pear/temp/maxminddb/ext/maxminddb.c:27:10: fatal error: maxminddb.h: No such file or directory
   27 | #include <maxminddb.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:192: maxminddb.lo] Error 1
ERROR: `make' failed
```

**Comment by mlocati** [comment]
@kocoten1992 you need to install the `libmaxminddb-dev` system package (`apt-get install libmaxminddb-dev` on debian/ubuntu, `apk add libmaxminddb-dev` on alpine).
