### ISSUE TITLE
Cannot compile the extension

### ISSUE THREAD

**Issue by pbudzon** [maxmind/MaxMind-DB-Reader-php#4]
Hello,

When trying to compile the extension I get the following error:

```
MaxMind-DB-Reader-php-master/ext/maxminddb.c:22:23: fatal error: maxminddb.h: No such file or directory
compilation terminated.
make: *** [maxminddb.lo] Error 1
```

Steps to reproduce:
1. Download the latest code from master
2. `cd ext`
3. `phpize`
4. `./configure`
5. `make`

I'm using PHP 5.5.5.

**Comment by kabudu** [comment]
I've installed ```libmaxminddb``` and I've run into the same issue.

**Comment by kabudu** [comment]
Probably a little late @pbudzon , but I found the solution. You'll need to add the path to the maxminddb header files to your configure command.

For a C++ compiler:

    ./configure CXXFLAGS="-I/path/to/header/files"

For a C compiler:

    ./configure CFLAGS="-I/path/to/header/files"

In my distribution (```alpine```), the header files are located here:
    
    /usr/local/include
