### ISSUE TITLE
error when install c extension for php7

### ISSUE THREAD

**Issue by lilongyue** [maxmind/MaxMind-DB-Reader-php#41]
after compiling and install of maxminddb . I start to config and install to get the maxminddb.so .
but when i restart the php7 service . i get this error: 
 NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/remi/php70/root/usr/lib64/php/modules/maxminddb.so' - /opt/remi/php70/root/usr/lib64/php/modules/maxminddb.so: undefined symbol: zval_used_for_init in Unknown on line 0

**Comment by oschwald** [comment]
Are you sure you used the `phpize` for PHP 7 and not an older version that you may have installed? Also, are you using at least version 1.1.0 of this library?

**Comment by lilongyue** [comment]
ok ,i will try your ideas.

**Comment by lilongyue** [comment]
i want also ask you another question as my server has a lot of request per second. The geolite-city-2 db is around 100MB . 100MB * 400 request is large memory? (say i have 400 request per second ). Is there any problem for fast requests?

**Comment by oschwald** [comment]
If you are using the extension, the database is memory mapped, which is shared between open instances. 400 requests for second should not be a problem.

**Comment by lilongyue** [comment]
Thank you very much

**Comment by oschwald** [comment]
Closing as it appears that you worked out the issue. Please let us know if that is not the case.

**Comment by jondavis0787** [comment]
Im getting this error now as well with cPanel
