### ISSUE TITLE
Reader::findMetadataStart runs forever on faulty files

### ISSUE THREAD

**Issue by eteubert** [maxmind/MaxMind-DB-Reader-php#42]
If the database file is faulty, findMetadataStart has to go through the whole file byte by byte, which is extremely slow and creates a timeout exception (for servers with default config of 30 seconds timeout).

I know I can (and probably should) check for the validity of the database file before using the reader. However, it would be nice if it could handle that case more gracefully.

**Comment by oschwald** [comment]
Per the [MaxMind DB spec](https://github.com/maxmind/MaxMind-DB/blob/master/MaxMind-DB-spec.md#database-metadata), the metadata will always be in the last 128 KB. We should probably just stop searching at that point.

**Comment by eteubert** [comment]
I am still hoping for a patch :)

Is it as simple as changing the [outer search loop](https://github.com/maxmind/MaxMind-DB-Reader-php/blob/master/src/MaxMind/Db/Reader.php#L241)?

```php
// from this
for ($i = 0; $i < $fileSize - $markerLength + 1; $i++) {

// ... to this?
for ($i = 0; $i < 128000 + 1; $i++) {
```

**Comment by oschwald** [comment]
You'd want the minimum the current number and 128k as a file could be less than 128k.
