### ISSUE TITLE
v1.1.2.tar.gz download is still says is v 1.1.1

### ISSUE THREAD

**Issue by leo020588** [maxmind/MaxMind-DB-Reader-php#48]
https://github.com/maxmind/MaxMind-DB-Reader-php/archive/v1.1.2.tar.gz
file: `ext/php_maxminddb.h`
`#define PHP_MAXMINDDB_VERSION "1.1.1"`

**Comment by oschwald** [comment]
Thanks. This was corrected in 1.1.3
