### ISSUE TITLE
Caching options

### ISSUE THREAD

**Issue by BassemN** [maxmind/MaxMind-DB-Reader-php#49]
Hello,

Thanks for this awesome library.
I'd like to see more caching options to accelerate lookup speed like caching the database file into memory using shmop PHP extension.

Thanks

**Comment by dark-rider** [comment]
Are there any caching options for MaxMind DB Reader at all?

By the way, some external examples include "reader->close();", but most and also MaxMind's own examples don't. Is the close command optional or should it even better not be used?

**Comment by oschwald** [comment]
@dark-rider, this library does not currently cache data across requests. If you are running into performance issues, I would first recommend trying the extension.

**Comment by oschwald** [comment]
Closing at this is largely a duplicate of #36.
