### ISSUE TITLE
Discrepancy in PHP library and C extension: Reader class marked `final`

### ISSUE THREAD

**Issue by venyii** [maxmind/MaxMind-DB-Reader-php#52]
The `Reader` class in the C extension is marked final (from what I understand):
https://github.com/maxmind/MaxMind-DB-Reader-php/blob/master/ext/maxminddb.c#L538

And the PHP library is not:
https://github.com/maxmind/MaxMind-DB-Reader-php/blob/master/src/MaxMind/Db/Reader.php#L14

This just came up while developing locally without the C extension and then running the tests in the CI env with the C extension installed which produces different results, for example when mocking the Reader class which will fail in the CI env.

**Comment by oschwald** [comment]
The intent was to make both final, but I guess that was not done for the PHP version. These classes were not designed to be subclassed.

That said, declaring the pure PHP version as final now would be a breaking change. A PR to remove the final on the extension along with a test to ensure the behavior of the two is the same would be gladly welcomed.
