### ISSUE TITLE
C extension does not support Reflection?

### ISSUE THREAD

**Issue by venyii** [maxmind/MaxMind-DB-Reader-php#53]
Take the following code:
```
$rm1 = new \ReflectionMethod('MaxMind\Db\Reader', '__construct');
$rm2 = new \ReflectionMethod('MaxMind\Db\Reader', 'get');

var_dump($rm1->getParameters());
var_dump($rm2->getParameters());
```

For the PHP library this will output:
```
array(1) {
  [0] =>
  class ReflectionParameter#5 (1) {
    public $name =>
    string(8) "database"
  }
}

array(1) {
  [0] =>
  class ReflectionParameter#5 (1) {
    public $name =>
    string(9) "ipAddress"
  }
}
```

But for the C extension:
```
array(0) {
}

array(0) {
}
```

This throws off static analyzers like https://github.com/phpstan/phpstan which rely on that information and throw errors (`Class MaxMind\Db\Reader constructor invoked with 1 parameter, 0 required.`) since you're passing a parameter to a method that _seemingly_ does not take any parameters.

This came up when running PHPStan in the CI env with the C extension installed, for now I exclude the test that calls the `Reader` class, but if it isn't too much trouble to support this, I'd be happy :)

**Comment by oschwald** [comment]
Thanks for bringing this up. I haven't found any great documentation on how to do this right, but it seems like `ZEND_BEGIN_ARG_INFO` and related macros might be involved. If you have any pointers, that would be helpful.

**Comment by venyii** [comment]
No sorry, I don't have a clue, but I'll post here if I find something

**Comment by venyii** [comment]
I think this got fixed by https://github.com/maxmind/MaxMind-DB-Reader-php/pull/75 🎉
