### ISSUE TITLE
Consider adding an autoloader (or 'require' statements)

### ISSUE THREAD

**Issue by orlitzky** [maxmind/MaxMind-DB-Reader-php#56]
I see that there's an open issue https://github.com/maxmind/MaxMind-DB-Reader-php/issues/34 to create a PECL package. To do that, you'll have to eliminate the dependency on composer, which would also help us create a Gentoo package. And to eliminate the dependency on composer, you'll need to either

* Ship your own autoload.php, so that composer isn't needed to generate it.
* Add back the few missing `require` statements. Since there are so few files in the library, this one makes more sense than a custom autoloader to me.

Either of those would also simplify the documentation, and let people run the tests from a git clone.

We can work around the issue with https://github.com/php-fedora/autoloader, but like they say, it would be nice if we didn't have to =)

**Comment by matthewslyman** [comment]
I'm currently using the raw PHP files with the require statements manually added back in. For total idiots like me who never bothered learning how to use Composer yet, this would be a boon.

**Comment by oschwald** [comment]
I don't think we will be replacing Composer as the recommended installation method. Most popular packages use Composer these days. This library will also work with the autoloaders present in various frameworks, as long as they comply with PSR-4.

That said, it might be worth including an example of how to load the classes manually, if for some reason, you cannot use an autoloader.

**Comment by orlitzky** [comment]
Composer will work fine even with the `require` statements present, or with your own autoload.php in the source tree (but unused if installed by composer). For an example of that, there's an autoloader that I helped add to php-redmine-api a while back,

  https://github.com/kbsali/php-redmine-api/blob/master/lib/autoload.php

If present, that file will use the composer autoloader; otherwise, it will use the custom one. That makes the instructions simple because you don't need to change them depending on whether or not you used composer to install the package -- either way, you just `require('lib/autoload.php')`. The main benefit however is that it works even without composer, which means that we can take the release tarball and run the tests, or check its SHA hash, without having to have a network connection or patch in our own autoloader.

I wouldn't want to make the experience for composer users worse, but rather make it better for everyone else. (So long as there's like, four files, in the library though -- a custom autoload.php would be more code than adding back the `require` statements.)

**Comment by oschwald** [comment]
I'd prefer not to add the `require` statements to the classes, but as I mentioned above, I'd be ok with PHP file that could be used by users not using an autoloader. Preferably, this script would live outside of `src/` and would be tested to ensure that it works going forward, both with the extension loaded and without.
