### ISSUE TITLE
Accept phpunit-5.x for test dependencies

### ISSUE THREAD

**Issue by orlitzky** [maxmind/MaxMind-DB-Reader-php#57]
While working on issue https://github.com/maxmind/MaxMind-DB-Reader-php/issues/56, I noticed that phpunit-5.7.15 works just fine for running the tests even though composer asks for the old phpunit-4.x series:

https://github.com/maxmind/MaxMind-DB-Reader-php/blob/a8ccb1501f78d3d56679d5ee498321c77707e9d3/composer.json#L25

Tested with php-5.6.32, php-7.0.25, and php-7.1.11 -- the whole suite passes for all of them.

**Comment by oschwald** [comment]
A version range would work. We need to continue support 4.x for older PHPs, but there is no reason why we can't use newer major versions on newer PHPs if there are no incompatibilities for our test suite.
