### ISSUE TITLE
extension does not care about open_basedir

### ISSUE THREAD

**Issue by bburnichon** [maxmind/MaxMind-DB-Reader-php#61]
https://github.com/maxmind/MaxMind-DB-Reader-php/blob/7abf5be62b08353c7bc69494f421f13503d6e8c0/ext/maxminddb.c#L130

Access is a very low level file operation. Not all low level accesses to database files should be authorized.
Going from Userland php to extension is no issue, but the reverse could cause some `open_basedir` errors. Database path could be passed from userland (so can sometimes be accessed by attackers) so internal path access php checks are mandatory.

**Comment by oschwald** [comment]
Thanks for raising this. We will look into it.

**Comment by bburnichon** [comment]
Thanks for fixing this and released a new version!
