### ISSUE TITLE
Please check for existence of file before include

### ISSUE THREAD

**Issue by Xuphey** [maxmind/MaxMind-DB-Reader-php#65]
Hi,

https://github.com/maxmind/MaxMind-DB-Reader-php/blob/9a941f47305a0eb0ca694a98c9a946a32a2a0b8f/autoload.php#L40

In the autoload script, please check the file existence at least.
Suppressing the error doesn't prevent it happening.

**Comment by oschwald** [comment]
Composer should not be using this file. If it is, it is a bug. How are you loading the dependency?

**Comment by Xuphey** [comment]
I loaded the autoload script of this project. When I change the script to the parent project geoip2 autoload, which generated by composer, the warnings go away.
