### ISSUE TITLE
[INFO] RPM packages

### ISSUE THREAD

**Issue by remicollet** [maxmind/MaxMind-DB-Reader-php#82]
Not an issue ;) for your information

php-maxminddb packages are now available in fedora official repository

See https://apps.fedoraproject.org/packages/php-maxminddb

Fedora users can simply install it with 

`dnf install php-maxminddb
`
CentOS / RHEL 7 users, after enabling EPEL repostiory, with

`yum install php-maxminddb
`

Perhaps worth something in the README.md file.

P.S. also available in my repository for other PHP versions

**Comment by oschwald** [comment]
Thanks! I'll leave this open as a reminder to update the `README.md` file.
