### ISSUE TITLE
How can you tell if the C extension is used?

### ISSUE THREAD

**Issue by lano1106** [maxmind/MaxMind-DB-Reader-php#88]
I thought that I could remove the maxmind-db/reader package with composer after having installed the C extension.

I'm too dumb with composer to do that. In the php info, I have the following:

MaxMind DB Reader | enabled
-- | --
maxminddb extension version | 1.4.1
libmaxminddb library version | 1.3.2

it seems to be a good indication that the C extension is used and not the PHP code. Would you agree?

**Comment by oschwald** [comment]
I'd recommend keeping `maxmind-db/reader` as it is still used for some small things with the extension. It sounds like you are good to go though.
